#%RAML 1.0
version: v1
title: Workday ERP API

types:
  Contact: !include exchange_modules/42d8e488-c27a-40fa-981c-359a73641d4f/contact/1.0.0/contact.raml

traits:
  client-id-required:
    queryParameters:
      client_id:
        type: string
      client_secret:
        type: string

/contacts:
  description: Creates or updates a contact
  post:
    is: [client-id-required]
    body:
      application/json:
        type: Contact
    responses:
      204:
        description: Acceptd contact

/contacts/{reference}:
  delete:
    is: [client-id-required]
    responses:
      204:
        description: Deleted contact