#%RAML 1.0
version: v3
title: Workday ERP API

types:
  Contact: !include exchange_modules/b43e4e64-3308-45f1-9599-bc9bc78957e6/contact/1.0.1/contact.raml

/contacts:
  description: Creates or updates a contact
  post:
    body:
      application/json:
        type: Contact
    responses:
      204:
        description: Acceptd contact