#%RAML 1.0
version: v1
title: Workday ERP API

types:
  Contact: !include  exchange_modules/82f78ed0-714c-47f0-b038-c0c1c061d2f3/contact/1.0.0/contact.raml

/contacts:
  description: Creates or updates a contact
  post:
    body:
      application/json:
        type: Contact
    responses:
      204:
        description: Acceptd contact

/contacts/{reference}:
  delete:
    responses:
      204:
        description: Deleted contact